# Generated by Django 4.2.2 on 2023-11-25 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_chatsession_delete_chatlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='New Session', max_length=300, null=True, verbose_name='session title'),
        ),
    ]
