# Generated by Django 4.2.2 on 2023-11-20 16:48

from django.db import migrations, models
import user.manager


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', user.manager.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='chat_logs',
            field=models.JSONField(blank=True, null=True, verbose_name='chat logs'),
        ),
    ]
