# Generated by Django 4.2.2 on 2023-11-24 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_chatlog_user'),
        ('user', '0004_remove_user_chat_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chat_log',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='api.chatlog'),
        ),
    ]
